server:
  port: 8084

spring:
  application:
    name: service-feign

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: ["health","info","hystrix.stream"]
